name: Create Release on Tag Push

on:
  push:
    tags:
      - "*.*.*"

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create ZIP file
        run: |
          # Exclude files specified in .gitattributes
          git archive -o myapp-${{ github.ref }}.zip HEAD $(git ls-files ':!:path/to/exclude')

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          files: |
            wp-lnc-bitcoin.zip
          body: |
            Release ${{ github.ref }}
            Add your release notes and description here.
