name: Create Release on Tag Push

on:
  push:
    tags:
      - "*.*.*"

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create ZIP file
        run: |
          # Get the current tag name
          TAG_NAME=$(git describe --tags --abbrev=0)

          # Create a temporary directory
          TEMP_DIR=$(mktemp -d)

          # Copy the files of the current tag to the temporary directory
          git archive $TAG_NAME | tar -x -C $TEMP_DIR

          # Create the ZIP file from the temporary directory
          zip -r wp-lnc-bitcoin.zip $TEMP_DIR

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          files: |
            wp-lnc-bitcoin.zip
          body: |
            Release ${{ github.ref }}
