name: Create Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Create ZIP archive
        run: zip -r wp-lnc-bitcoin.zip .
        working-directory: ./dist

      - name: Upload ZIP archive
        uses: actions/upload-artifact@v2
        with:
          name: wp-lnc-bitcoin.zip
          path: wp-lnc-bitcoin.zip
